[package]
name = "netcanv-renderer-opengl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { workspace = true }
winit = { version = "0.29.15", features = ["serde", "rwh_05"] }
glutin = "0.31.2"
glutin-winit = "0.4.2"
raw-window-handle = "0.5.2"
glow = "0.12.3"
memoffset = "0.9.0"
swash = "0.1.8"
smallvec = { version = "1.11.1", features = ["const_generics"] }
glam = "0.24.2"

netcanv-renderer = { path = "../netcanv-renderer" }
