[package]
name = "netcanv-renderer-opengl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.40"
winit = { version = "0.27.4", features = ["serde"] }
glutin = "0.29.1"
glow = "0.11.2"
memoffset = "0.6.4"
swash = "0.1.6"
smallvec = { version = "1.7.0", features = ["const_generics"] }
glam = "0.19.0"

netcanv-renderer = { path = "../netcanv-renderer" }
